Repository wecode-bootcamp-korea/24-1st-WTP-frontend, pull requests merged in 2021-09, with the labels that each got.

#1 [24기 김태수] Add: Navbar 레이아웃 구현 완료
  public/images/AtchaPedia_Logo_Big.png
  public/images/AtchaPedia_Logo_Small.png
  public/images/Atcha_Pedia_Logo_reversed.png
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/pages/Main/Main.js
  src/styles/variables.scss
Labels: Status: 수정 요청

#6 [24기 김영호]Add : Footer 레이아웃 완료
  public/images/blogger.png
  public/images/facebook.png
  public/images/twitter.png
  src/Routes.js
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Footer/FooterData.js
  src/pages/Main/Main.js
Labels: Status: 리뷰 요청

#9 [24기 김태수] 로그인, 회원가입 모달 간 버튼으로 연동 구현
  public/data/moviesData.json
  src/components/Button/Button.js
  src/components/Button/Button.scss
  src/components/Form/Form.js
  src/components/Form/Form.scss
  src/components/FormLayout/FormLayout.js
  src/components/FormLayout/FormLayout.scss
  src/components/Input/Input.js
  src/components/Input/Input.scss
  src/components/Login/Login.js
  src/components/Login/Login.scss
  src/components/Modal/Modal.js
  src/components/Modal/Modal.scss
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/SearchBar/SearchBar.js
  src/components/SearchBar/SearchBar.scss
  src/components/SearchInput/SearchInput.js
  src/components/SearchInput/SearchInput.scss
  src/components/Validation/Validation.js
  src/components/Validation/Validation.scss
  src/config.js
  src/pages/Main/Main.js
Labels: Status: 추가 기능 구현중

#10 [24기 김영호] Add : MyMovies 레이아웃 완료
  public/data/WantSeeMovies.json
  src/Routes.js
  src/pages/MyMovies/MyMovies.js
  src/pages/MyMovies/MyMovies.scss
Labels: Status: Conflict 해결 요청

#2 [24기 김영현 | Feature/contents] Add: 별점 기능 구현 완료
  package-lock.json
  public/data/MockComments.json
  public/data/MockMovieInfo.json
  public/favicon.ico
  public/favicon1.ico
  public/favicon2.ico
  public/favicon3.ico
  public/images/3f2c70fa235fcd74e64cacf38230e85d.jpeg
  public/images/6fffe5c50f39dbcad014570c3da67b13.jpeg
  public/images/a4d2dd681002aaf17c39edfb948a217d.jpeg
  public/images/bb2e1eaf00d3d86b835e3d8e6a30523a.jpeg
  public/images/gallery.jpeg
  public/images/poster.jpeg
  public/images/trailer.jpeg
  public/index.html
  src/Routes.js
  src/assets/icons/half-star-shape.svg
  src/assets/icons/png-clipart-wand-magician-others-miscellaneous-black.cur
  src/assets/icons/pointed-star-yellow1.png
  src/assets/icons/pointed-star.svg
  src/assets/icons/star4.svg
  src/config.js
  src/pages/Contents/Aside/Aside.js
  src/pages/Contents/Aside/Aside.scss
  src/pages/Contents/BasicInfo/BasicInfo.js
  src/pages/Contents/BasicInfo/BasicInfo.scss
  src/pages/Contents/CommentModal/CommentModal.js
  src/pages/Contents/CommentModal/CommentModal.scss
  src/pages/Contents/Comments/Comments.js
  src/pages/Contents/Comments/Comments.scss
  src/pages/Contents/Contents.js
  src/pages/Contents/Contents.scss
  src/pages/Contents/InfoAct/InfoAct.js
  src/pages/Contents/InfoAct/InfoAct.scss
  src/pages/Contents/MovieInfo/MovieInfo.js
  src/pages/Contents/MovieInfo/MovieInfo.scss
  src/pages/Contents/Process/Process.js
  src/pages/Contents/Process/Process.scss
  src/pages/Contents/SimilarThings/SimilarThings.js
  src/pages/Contents/SimilarThings/SimilarThings.scss
  src/pages/Main/Main.js
  src/pages/Main/Movie/Movie.js
  src/styles/reset.scss
  src/styles/variables.scss
Labels: Status: 리뷰 요청

#14 Modify: 마이페이지 평가한 영화 목록 제공 및 코드 리팩토링
  src/components/Button/Button.js
  src/components/Footer/Footer.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Validation/Validation.js
  src/components/Validation/Validation.scss
  src/config.js
  src/pages/Contents/Contents.js
  src/pages/Contents/SimilarThings/SimilarThings.js
  src/pages/Main/Main.js
  src/pages/Main/Movie/Movie.scss
  src/pages/Main/MoviesCarousel/MoviesCarousel.scss
  src/pages/MyMovies/MyMovies.js
  src/pages/Profile/Profile.js
Labels: Status: 리뷰 요청
